# Generated by Django 5.0.6 on 2024-07-04 19:34

import orm_2.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_2', '0002_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to=orm_2.helpers.SaveMedia.save_book_image_path),
        ),
    ]
